eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://alnt-registry:8761/eureka/}
spring:
  datasource:
    url: ${APP_DB_URL:jdbc:sqlserver://10.9.40.32;instanceName=SQLEXPRESS14;database=mcpdbqa}
    username: ${APP_DB_USER:sa}
    password: ${APP_DB_PASSWORD:Onity@123}
    driver-class: ${APP_DB_DRIVER_CLASS:com.microsoft.sqlserver.jdbc.SQLServerDriver}
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    factoryClassLocation: org.apache.naming.factory.BeanFactory
    maxIdleTime: 600
    maxPoolSize: 100
    minPoolSize: 5
    initialPoolSize: 5
    acquireIncrement: 5
    numHelperThreads: 20

  jpa:
    database-platform: ${APP_DB_JPA_DIALECT:org.hibernate.dialect.SQLServerDialect}
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.use_nationalized_character_data: ${NATIONAL_CHARSET:true}


  artemis:
    mode: native
    host: ${ARTEMIS_HOST:alnt-artemis}
    port: ${ARTEMIS_PORT:61617}
    embedded:
      enabled: false

redis:
  host: ${REDIS_HOST:alnt-redis}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  session:
    host: ${REDIS_HOST:alnt-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}  
    
queueBrowser:
  names:
   - "sendMail"
  cronInterval: "0 0/1 * * * ?"
  messageDelayInMinutes: 1   

ssoConfigurations:
  client:
    clientId: ${CLIENT_ID:39971172-0873-4d99-9ca6-a6adb4a7fb5e}
    clientSecret: ${CLIENT_SECRET:6WX8FanYL+GwR6SjocdbPLFC9/NpeOwXJOs+w5JZpGo=}
    accessTokenUri: ${ACCESS_TOKEN_URI:https://login.windows.net/cae20826-e5c9-4c08-8984-c70e736bf19f/oauth2/token}
    userAuthorizationUri: ${USER_AUTH_URI:https://login.windows.net/cae20826-e5c9-4c08-8984-c70e736bf19f/oauth2/authorize}
    successUrl: ${successUrl:http://localhost:4000}
    domainHint: ${DOMAIN_NAME:}
    preEstablishedRedirectUri: ${preEstablishedRedirectUri:http://localhost:4000/sso/login/}

azureAD:
  applicationDomain: ${APPLICATION_DOMAIN:badgingportalqa.onmicrosoft.com}
  clientId: ${CLIENT_ID:39971172-0873-4d99-9ca6-a6adb4a7fb5e}
  clientSecret: ${CLIENT_SECRET:6WX8FanYL+GwR6SjocdbPLFC9/NpeOwXJOs+w5JZpGo=}

application:
  domainName: ${APPLICATION_DOMAIN:badgingportalqa.onmicrosoft.com} #alertenterpriseMCP.onmicrosoft.com, alert  

report:
  server:
    url: ${REPORT_SERVER_URL:http://10.9.41.174:8090} #https://qa.badgingportal.com

hystrix:
 command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
logging:
  level:
    com.alnt: ${ALNT_LOG_LEVEL:INFO}
    org.springframework: ${SPRINGFRAMEWORK_LOG_LEVEL:ERROR}
    com.netflix: ${NEXTFLIX_LOG_LEVEL:ERROR}
    
applimits:
  enabled : true
  partners: 100
 

  

  